query devPosts {
  devPosts: posts(orderBy: date_DESC, where: {tags_contains_all: tech}) {
    articleLink
    bookImage {
      url
    }
    bookImageAltText
    bookImageLink
    category
    coverImage {
      url
    }
    coverImageAltText
    coverImageSourceName
    coverImageSourceUrl
    date
    excerpt
    publication
    publicationName
    publishedAt
    slug
    title
  }
}