fragment experienceFields on Experience {
  dates
  id
  organization
  organizationLink
  roleType
  summary {
    html
  }
  title
}

query technicalExperiencesQuery {
  technicalExperiences: experiences(where: {roleType: Tech}, orderBy: displayOrder_DESC) {
    ...experienceFields
  }
}

query communityExperiencesQuery {
	communityExperiences: experiences(where: {roleType: Community}, orderBy: displayOrder_DESC) {
    ...experienceFields
  }
}
