query featuredPublications($numPosts: Int) {
  featuredPublications: posts(first: $numPosts, orderBy: date_DESC, where: {publication: true, tags_contains_all: featured}) {
    id
    articleLink
    bookImageAltText
    bookImage {
      url
    }
    category
    coverImageAltText
    coverImageSourceUrl
    excerpt
    date
    publication
    publicationName
    slug
    tags
    title
  }
}