query postQuery($slug: String) {
  post: post(where: {slug: $slug}) {
    bookImageAltText
    bookImageLink
    category
    content {
      html
    }
    coverImage {
      url
    }
    coverImageAltText
    coverImageSourceName
    coverImageSourceUrl
    date
    id
    title
  }
}