query postQuery($slug: String) {
  post: post(where: {slug: $slug}) {
    bookImage {
      url
    }
    bookImageAltText
    bookImageLink
    category
    contentMd
    coverImage {
      url
    }
    coverImageAltText
    coverImageSourceName
    coverImageSourceUrl
    date
    id
    title
  }
}